

insert into php_interview_questions(id,question,answer) values('2',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");
insert into php_interview_questions(id,question,answer) values('3',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");
insert into php_interview_questions(id,question,answer) values('4',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");
insert into php_interview_questions(id,question,answer) values('5',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");
insert into php_interview_questions(id,question,answer) values('6',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");


insert into php_interview_questions(id,question,answer) values('7',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");
insert into php_interview_questions(id,question,answer) values('8',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");
insert into php_interview_questions(id,question,answer) values('9',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");
insert into php_interview_questions(id,question,answer) values('10',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");
insert into php_interview_questions(id,question,answer) values('11',"While trying to learn the American manual alphabet I discovered a computer method to read text as if it were being finger spelled. All one needs is a Windows word-processor (or something equivalent) and a sign-language font.
I'm quite happy with the result and think it will interest any persons who are learning the American manual alphabet themselves. The method should also work for other manual alphabets (such as the two-handed alphabet used in the UK) should fonts ever be made for them.","The process is illustrated below using the Gallaudet font. You can download the Gallaudet font from the Yamada Language Center at the University of Oregon.");